declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_AUTH_API_URL: string
    NEXT_PUBLIC_ORDER_API_URL: string
    NEXT_PUBLIC_RESTAURANT_API_URL: string
    NEXT_PUBLIC_PAYMENT_API_URL: string
    NEXT_PUBLIC_DELIVERY_API_URL: string
    NEXT_PUBLIC_LOCATION_API_URL: string
    NEXT_PUBLIC_NOTIFICATION_API_URL: string
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string
  }
}
