apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodhub-frontend
  labels:
    app: foodhub-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foodhub-frontend
  template:
    metadata:
      labels:
        app: foodhub-frontend
    spec:
      containers:
      - name: foodhub-frontend
        image: foodhub-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          value: "http://api-gateway-service:5000"
        - name: NEXT_PUBLIC_AUTH_SERVICE_URL
          value: "http://auth-service:5007"
        - name: NEXT_PUBLIC_RESTAURANT_SERVICE_URL
          value: "http://restaurant-service:5008"
        - name: NEXT_PUBLIC_ORDER_SERVICE_URL
          value: "http://order-service:5001"
        - name: NEXT_PUBLIC_PAYMENT_SERVICE_URL
          value: "http://payment-service:5004"
        - name: NEXT_PUBLIC_DELIVERY_SERVICE_URL
          value: "http://delivery-service:5010"
        - name: NEXT_PUBLIC_LOCATION_TRACKER_URL
          value: "http://location-tracker-service:5009"
        - name: NEXT_PUBLIC_NOTIFICATION_SERVICE_URL
          value: "http://notification-service:5003"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: foodhub-frontend-service
spec:
  selector:
    app: foodhub-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
